### ISSUE TITLE
form c/team member/director/format

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1893]
change format of DIRECTOR page to look like this
![image](https://cloud.githubusercontent.com/assets/21366183/20989357/5b640382-bca2-11e6-89ab-972c066fc65c.png)
![image](https://cloud.githubusercontent.com/assets/21366183/20989253/0b18e000-bca2-11e6-8c64-3555afe5f8c4.png)

**Comment by arthuryip723** [comment]
To make the fields not required, I think we need to change the back-end schema.
@vladyslav2

**Comment by OstapL** [comment]
Fixed 
Delete Board Service End Date
Change text label - Employment Start Date
#1946

**Comment by vladyslav2** [comment]
@morganm24 if sometimes not fixed please create new issue
here is few issues it is not convenient to work with that issue right now
