### ISSUE TITLE
Risks/FAQ

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#567]
@arthuryip723 @OstapL @leonstiel 

1)there should not be gray color for font. Only black.
And delete here "See all FAQ/Risks" @OstapL 

2)The accordions do not working correct. Please check it.  @arthuryip723 

![2016-09-13 17 06 17](https://cloud.githubusercontent.com/assets/20995691/18477234/9863a4a0-79d5-11e6-8c5a-0432cce3614b.png)
![2016-09-13 17 06 39](https://cloud.githubusercontent.com/assets/20995691/18477233/9860ba24-79d5-11e6-8b1e-fa2c7b7894ce.png)

**Comment by OstapL** [comment]
Fixed #583
change color 
delete link - see all 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/86

**Comment by MariaKravchuk** [comment]
@arthuryip723 the accordions look better now but still not every time. 
Please, just clicking for a couple time accordions, for example Risks or FAQ and check them.

**Comment by MariaKravchuk** [comment]
@vladyslav2 this issue still does not complete

**Comment by vladyslav2** [comment]
fixed
please check @MariaKravchuk
