### ISSUE TITLE
Text for tips

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#621]
@vladyslav2 @leonstiel 

Giving you the texts of tips for Create Company/Campaign pages

1)Create company page

field Description:

**Explain what your company does in a way that everyone  will understand. 
“If you can’t explain it simply, you don’t understand it well enough.” – Albert Einstein**

![2016-09-14 15 30 00](https://cloud.githubusercontent.com/assets/20995691/18512141/55e32a40-7a90-11e6-856a-c002f9609def.png)

2)Create campaign/General information page

field Pitch:

**What is your edge? Do you have a competitive advantage? Why should investors want to invest 
in your company?**

field Intended Use of Proceeds:

**Why are you raising capital, and what do  you intend to do with it?**

field Business Model:

**How do you make money?**

FAQ, field question:

**Create your own Q&A section. What questions do you frequently recieve or what would you 
want investors to know ?** 

Additional information, field Optional Additional Sections:

 **Is there anything else you want to tell your potential investors?**

![2016-09-14 15 32 43](https://cloud.githubusercontent.com/assets/20995691/18512478/ff2c50bc-7a91-11e6-9b93-9627d23a0e8c.png)
![2016-09-14 15 43 22](https://cloud.githubusercontent.com/assets/20995691/18512479/ff2d97f6-7a91-11e6-87c7-aa66158de8f5.png)

3) Create campaign/Media page

field Header Image:

**This is the image that will appear at the top of your campaign. A minimum size of 1600x400 is recommended.**

field Thumbnail Picture:

**This image entices investors to view your campaign. A minimum size of 1600x400 is recommended.**

field Gallery:

**We recommend uploading 8 images that represent your service of business. These images will be displayed in a gallery format.**

Field Main Video for Campaign:

**You Tube or Vimeo links only please.**

Field Optional Video for Campaign:

**You Tube or Vimeo links only please.**

![2016-09-14 15 50 29](https://cloud.githubusercontent.com/assets/20995691/18512697/fec453d0-7a92-11e6-8991-eb2b49462b78.png)

4)Create campaign/Team members

field Where did you grow up?:

**Why do we ask? These affinity based questions can help us share your campaign with potential investors with similar backgrounds.**

![2016-09-14 15 51 41](https://cloud.githubusercontent.com/assets/20995691/18512780/583c318a-7a93-11e6-9b2c-f875bb4737c5.png)

5)Create campaign/Specifics

fields Our Minimum/Maximum Total Raise is:

 **Important Information About the Amount of Your Raise**

**The requirement is based upon your Maximum Raise Amount:
“If $100,000 or less”
Financials have to be signed by CEO and total 
income, taxable income and total tax reflected on
federal return must be included.  If reviewed or 
audited financials available, they must be provided
instead.**
**“If $100,001-$500,000”
Financials have to be signed by independent 
accountant.  If audited financials available, they 
must be provided instead"
“If $500,001-$1,000,000”**
**Financials have to be signed by an independent 
auditor UNLESS this is your first reliance on 
Regulation Crowdfunding, in which case financials 
must be signed by an independent accountant. 
If audited statements are available, they must be 
provided insteadite here.**

Field Link to calculators:

**Our calculators can help you:
1. Derive your valuation;
2. Choose the right security;
3. Know how much money to raise**

Fields Minimum/Maximum № of Shares:

![2016-09-14 15 59 45](https://cloud.githubusercontent.com/assets/20995691/18513013/4fa14d34-7a94-11e6-8896-8943d570a009.png)

![2016-09-14 16 00 41](https://cloud.githubusercontent.com/assets/20995691/18513043/68c99ee2-7a94-11e6-8cbf-027804a798ed.png)

Fields Minimum/Maximum Equity Offered:

![2016-09-14 16 02 01](https://cloud.githubusercontent.com/assets/20995691/18513091/9bb3389a-7a94-11e6-9c79-c45c10546e84.png)

![2016-09-14 16 02 50](https://cloud.githubusercontent.com/assets/20995691/18513111/b51a537c-7a94-11e6-8f76-f3a84815c681.png)

**Comment by vladyslav2** [comment]
we need to update help_text on the models

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/ef2243e4349cacab43c903ef335a1bf73cebab5b)

**Comment by MariaKravchuk** [comment]
Following tips are still do not exist on the site!

FAQ, field question:

Create your own Q&A section. What questions do you frequently recieve or what would you 
want investors to know ?

Additional information, field Optional Additional Sections:

Is there anything else you want to tell your potential investors?

field Gallery:

We recommend uploading 8 images that represent your service of business. These images will be displayed in a gallery format.

Field Main Video for Campaign:

You Tube or Vimeo links only please.

Field Optional Video for Campaign:

You Tube or Vimeo links only please.

field Where did you grow up?:

Why do we ask? These affinity based questions can help us share your campaign with potential investors with similar backgrounds.
