### ISSUE TITLE
Team member/Create company page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#868]
@vladyslav2 @leonstiel 
Why here does not appear appropriate information and image which I filled?
![2016-09-26 20 26 28](https://cloud.githubusercontent.com/assets/20995691/18844951/43af0352-8428-11e6-8f0d-8959c9545770.png)

@vladyslav2  we added button "cancel" in the form for team member
![2016-09-27 12 49 18](https://cloud.githubusercontent.com/assets/20995691/18868468/fde21a42-84b0-11e6-9ba5-02932ca8c441.png)

Please Set it so that it allows for user to leaves this form without saving any information.

here updated layout with new button
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3ATeam+members.psd

**Comment by vladyslav2** [comment]
@fixed

**Comment by MariaKravchuk** [comment]
@vladyslav2 "cancel" button still does not allow to back 
![2016-10-03 13 59 31](https://cloud.githubusercontent.com/assets/20995691/19035351/b649a1e4-8971-11e6-9025-9ed2765bce51.png)
